# Generated by Django 3.0.8 on 2020-07-12 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matrix", "0002_communityuserinvitation_managedcommunity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="managedcommunity",
            options={"verbose_name_plural": "Managed communities"},
        ),
    ]
