name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install black
      run: pip3 install black
    
    - name: coding style checker
      run: python3 -m black --check -vv $GITHUB_WORKSPACE
